### ISSUE TITLE
Click on slider doesn't set the value in model

### ISSUE THREAD

**Issue by aniketrk** [seiyria/angular-bootstrap-slider#72] opened 2015-06-17 13:52 UTC
Click on slider doesn't set the value in model. Only when we slide the slider that time the value is set. Can you please help me with the solution ?

**Comment by seiyria** [comment] 2015-06-17 13:53
duplicate of #71. seriously, that one was just opened 5 minutes prior to yours.

**Closed by seiyria** 2015-06-17 13:53 UTC
